Repository githubschool/on-demand-github-pages, pull requests merged in 2018-05, with the labels that each got.

#2970 New time Stamp
  _pages/fongj2.yaml
  _pages/itstorro.yaml
Labels: Help Wanted

#2491 Adding my changes
  _pages/1dhiman.yaml
  _pages/AidanCooper.yaml
  _pages/Raybeecham.yaml
Labels: Help Wanted, bug

#2945 Created new file
  _pages/GitHub85-add-page.yaml
Labels: invalid
